version: '3.8'

services:
  redis-prod:
    image: redis:alpine
    container_name: cache-prod
    command: --port 6380
    ports:
      - 6380:6380
    expose:
      - '6380'
    networks:
      - coolify
    restart: unless-stopped

  app-prod:
    build: ./
    container_name: calculator-prod
    depends_on:
      - redis-prod
    ports:
      - 8010:8010
    networks:
      - coolify
    environment:
      - PORT=${PORT:-8010}
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL_PROD}
    restart: unless-stopped

networks:
  coolify:
    external: true
