version: '3.8'

services:
  redis-prod:
    image: redis:alpine
    container_name: cache-prod
    command: --port 6380
    ports:
      - 6380:6380
    expose:
      - '6380'
    networks:
      - prod-network
    restart: unless-stopped

  redis-insight-prod:
    image: redis/redisinsight:latest
    environment:
      - RI_APP_PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - redis-prod
    networks:
      - prod-network
    restart: unless-stopped

  app-prod:
    build: ./
    container_name: calculator-prod
    depends_on:
      - redis-prod
    ports:
      - 8010:8010
    networks:
      - prod-network
    environment:
      - PORT=${PORT:-8010}
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL_PROD}
    restart: unless-stopped

networks:
  prod-network:
    name: prod-network
