export enum ErrorsDescriptions {
  GET_COORDS_ERROR = 'GET_COORDS_ERROR',
  GET_DISTANCE_ERROR = 'GET_DISTANCE_ERROR',
  GET_DELIVERY_COST_ERROR = 'GET_DELIVERY_COST_ERROR',
  OVERWEIGHT_ERROR = 'OVERWEIGHT_ERROR',
  NO_TEMPLATE_SIZE_ERROR = 'NO_TEMPLATE_SIZE_ERROR'
}
